CREATE TABLE `users` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`first_name`	TEXT NOT NULL,
	`last_name`	TEXT NOT NULL
);
CREATE TABLE "subscriptions" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`user_id`	INTEGER NOT NULL,
	`query_period`	INTEGER NOT NULL DEFAULT 60,
	`url`	TEXT NOT NULL,
	`last_query`	TIMESTAMP DEFAULT 0,
	FOREIGN KEY(`user_id`) REFERENCES `users.id`
);
CREATE TABLE `sent_offers` (
	`user_id`	INTEGER NOT NULL,
	`url`	TEXT NOT NULL,
	FOREIGN KEY(`user_id`) REFERENCES `users.id`
);
COMMIT;